name: Refresh Leaderboard

on:
  push:
    branches:
      - main
  schedule:
    - cron:  '0 */30 * * *'

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Update Leaderboard
        run: |
          node update-data ${{ secrets.SESSION_COOKIE }}

      - name: commit changes
        run: |
          git config user.name gh-actions
          git config user.email gh-actions@github
          git commit -am "Update data.js"
          git push origin main
